schema: ../../backend-nextjs/apollo/type-defs.graphqls
schemaEntrypoint: ../../backend-nextjs/apollo/type-defs.graphqls
documents: '**/*.graphql'
cacheDir: __generated__/__generated__/__generated__ # 避免生成的檔案在parent folder
plugins:
  - typescript
  - typescript-operations
  - typescript-react-apollo
config:
  preResolveTypes: true # 產生flatten-type，避免Pick<...>，增加易讀性
