apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  # annotations:
  #   dev.okteto.com/generate-host: 'true'
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: webapp
              servicePort: 3000
