apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: conote
build:
  artifacts:
    - image: conote-backend
      context: .
      docker:
        dockerfile: Dockerfile
        target: builder
    # - image: conote-backend
    #   context: .
    #   docker:
    #     dockerfile: Dockerfile
    #     target: backend
deploy:
  # helm:
  #   releases:
  #     - name: postgres
  #       chartPath: bitnami/postgresql # Need to add repo first `helm repo add bitnami https://charts.bitnami.com/bitnami`
  #       remote: true
  #       setValues:
  #         postgresqlUsername: 'postgresuser'
  #         postgresqlPassword: 'postgrespassword'
  kustomize:
    paths:
      - k8s
  # - overlays/dev
# profiles:
#   - name: prod
#     deploy:
#       kustomize:
#         paths:
#           - overlays/prod
#   - name: staging
#     deploy:
#       kustomize:
#         paths:
#           - overlays/staging
