# References
# - https://github.com/GoogleCloudPlatform/microservices-demo
# - https://github.com/GoogleCloudPladtform/solutions-modern-cicd-anthos/blob/master/starter-repos/online-boutique/skaffold.yaml
# - helm https://github.com/GoogleContainerTools/skaffold/tree/main/examples/helm-remote-repo

apiVersion: skaffold/v2beta28
kind: Config
build:
  artifacts:
    - image: conote-webapp-image
      context: .
      docker:
        dockerfile: './k8s/docker/Dockerfile.webapp'
    # - image: conote-dbbackup-image
    #   # context: './k8s/images'
    #   docker:
    #     dockerfile: './Dockerfile.dbbackup'
deploy:
  kustomize:
    paths:
      - k8s/dev
    buildArgs: ['--load-restrictor LoadRestrictionsNone']
profiles:
  - name: gcb
    build:
      # artifacts:
      # - image: conote-webapp-image
      #   context: .
      #   kaniko:  # Fail with yarn workspace
      #     cache: {}
      googleCloudBuild:
        projectId: conote-webapp
        timeout: 4000s
  - name: minikube
    activation:
      - command: debug
      - kubeContext: minikube
#   - name: dev
#     deploy:
#       kubeContext: docker-desktop
#   - name: prod
#     deploy:
#       kustomize:
#         paths:
#           - overlays/prod
#   - name: staging
#     deploy:
#       kustomize:
#         paths:
#           - overlays/staging
