# @see
# - https://github.com/GoogleCloudPlatform/microservices-demo
# - https://github.com/GoogleCloudPladtform/solutions-modern-cicd-anthos/blob/master/starter-repos/online-boutique/skaffold.yaml
# - helm: https://github.com/GoogleContainerTools/skaffold/tree/main/examples/helm-remote-repo

apiVersion: skaffold/v2beta16
kind: Config
build:
  artifacts:
    - image: conote-web
      context: .
      # docker:
      #   dockerfile: Dockerfile
      #   target: builder
deploy:
  # helm:
  #   releases:
  #     - name: postgres-release
  #       repo: https://charts.bitnami.com/bitnami
  #       remoteChart: postgresql
  #       setValues:
  #         postgresqlUsername: 'postgresuser'
  #         postgresqlPassword: 'postgrespassword'
  kustomize:
    paths:
      - k8s/dev
    buildArgs: ['--load-restrictor LoadRestrictionsNone']
# profiles:
#   - name: dev
#     deploy:
#       kubeContext: docker-desktop
#   - name: prod
#     deploy:
#       kustomize:
#         paths:
#           - overlays/prod
#   - name: staging
#     deploy:
#       kustomize:
#         paths:
#           - overlays/staging
