# Code https://github.com/Microsoft/vscode-remote-try-node
ARG VARIANT="14-buster"
# FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:0-${VARIANT} as base
FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:0-14-buster AS base
# FROM node:14-buster AS base

# Copy whole app to workspace
WORKDIR /workspace
COPY . ./

# Build lib packages first
WORKDIR /workspace/lib/editor
# TODO: 目前只要app裡的各個file編輯了就需要re-install，應該要將install獨立出來做成cache
# Copy the package.json as well as the package-lock.json and install
# the dependencies. This is a separate step so the dependencies
# will be cached unless changes to one of those two files
# are made.
# COPY package.json package-lock.json ./client/
RUN yarn

FROM base AS backend-dev

WORKDIR /workspace/backend
RUN yarn

FROM base AS frontend-dev

WORKDIR /workspace/frontend/web
RUN yarn

FROM frontend-dev AS frontend-build

WORKDIR /workspace/frontend/web
RUN yarn build

FROM nginx:1.17.0-alpine AS frontend-deploy

COPY --from=frontend-build /workspace/frontend/web/build /var/www

# Copy our custom nginx config
COPY ./configs/nginx.conf /etc/nginx/nginx.conf

# Expose port 80
EXPOSE 80

ENTRYPOINT ["nginx","-g","daemon off;"]
