# encoding: utf-8
# The secrets file should not be checked into Git. It's published only for demonstration purpose.
secretGenerator:
  - literals:
      - username=postgresuser
      - password=postgrespassword
    name: postgres-user-pass
  - literals:
      - url=postgresql://postgresuser:postgrespassword@conote-postgres/prisma?schema=public
    name: postgres-database-url
resources:
  - backend.yml
  - frontend.yml
  - postgres.yml
  - ingress.yml
images:
  - name: conote-frontend
  - name: conote-backend
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
