apiVersion: v1
kind: Service
metadata:
  name: conote-frontend
  labels:
    app: conote
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: conote
    tier: frontend
  ports: # Forward incoming connections on port 80 to the target port 80 in the Pod
    - port: 80
      targetPort: http-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conote-frontend
  labels:
    app: conote
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conote
      tier: frontend
  template:
    metadata:
      labels:
        app: conote
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: conote-frontend # Local build
          command: ['nginx']
          args: ['-g', 'daemon off;']
          ports:
            - name: http-server
              containerPort: 80
          # command: ['sleep', 'infinity']
