# encoding: utf-8
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - frontend.yml
  - backend.yml
  - postgres.yml
  - ingress.yml
images:
  # - name: conote-frontend
  - name: conote-backend

patchesStrategicMerge:
  - env.yaml

# The secrets file should not be checked into Git. It's published only for demonstration purpose.
secretGenerator:
  - literals:
      - username=postgresuser
      - password=postgrespassword
    name: postgres-user-pass
  - literals:
      - url=postgresql://postgresuser:postgrespassword@conote-postgres/prisma?schema=public
    name: postgres-database-url
# configMapGenerator:
#   - name: conote-configmap
#     envs:
#       - .env
