apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-not-use-now
spec:
  template:
    spec:
      containers:
        - name: web-not-use-now
          env:
            # - name: IEX_TOKEN
            #   value: ${IEX_TOKEN}
            - name: AUTH0_SECRET
              value: ${AUTH0_SECRET}
            - name: AUTH0_BASE_URL
              value: ${AUTH0_BASE_URL}
            - name: AUTH0_ISSUER_BASE_URL
              value: ${AUTH0_ISSUER_BASE_URL}
            - name: AUTH0_CLIENT_ID
              value: ${AUTH0_CLIENT_ID}
            - name: AUTH0_CLIENT_SECRET
              value: ${AUTH0_CLIENT_SECRET}
            # - name: DATABASE_URL
            #   value: ${DATABASE_URL}
            - name: APP_TOKEN_SECRET
              value: ${APP_TOKEN_SECRET}
            - name: APP_BOT_EMAIL
              value: ${APP_BOT_EMAIL}
