apiVersion: v1
kind: Pod
metadata:
  name: workload-identity-test
  namespace: default
spec:
  containers:
    - name: workload-identity-test
      image: conote-dbbackup-image
      # image: google/cloud-sdk:slim
      env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: conote-release-postgresql
              key: password
        - name: GCLOUD_STORAGE_BUCKET_DB_BACKUP
          value: konote-export-zip

      # command: ['sleep', 'infinity']
      command: ['/bin/sh']
      args:
        - -c
        - DUMP_FILE=/tmp/db_prisma-$(date +%Y%m%d_%H%M%S).dump && pg_dump --host conote-release-postgresql -U postgresuser -d prisma -p 5432 -Fc > $DUMP_FILE && gcloud storage cp $DUMP_FILE gs://${GCLOUD_STORAGE_BUCKET_DB_BACKUP}/

  serviceAccountName: storage-api-consumer-ksa
  nodeSelector:
    iam.gke.io/gke-metadata-server-enabled: 'true'
