schema: apollo/type-defs.graphqls
documents: '**/*.graphql'
cacheDir: .cache
plugins:
  - typescript-operations
  - typescript-react-apollo
config:
  enumsAsTypes: true
  preResolveTypes: true # produce flatten-type, avoid Pick<...>
  scalars: # mapping to typescript types
    BigInt: BigInt
    JSON: object
    DateTime: 'string | Date'
