apiVersion: skaffold/v2beta29
kind: Config
deploy:
  kubectl:
    manifests:
      - 'k8s/deployment/pubsub-with-secret.yaml'
profiles:
  - name: gcb
    build:
      artifacts:
        - image: db-backup-image
          context: .
          kaniko:
            cache: {}
      googleCloudBuild:
        projectId: conote-web-project
        timeout: 4000s
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
        - image: db-backup-image
          context: .
          sync:
            manual:
              # Sync all the javascript files that are in the src folder
              # with the container src folder
              - src: 'src/**/*.py'
                dest: 'workspace/src'
